name: dbt Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dbt
      run: |
        pip install dbt-core dbt-postgres
        
    - name: Check dbt project structure
      run: |
        cd dbt_project
        dbt debug --no-write-json || echo "No database connection - this is expected"
        dbt parse --no-write-json
        echo "✅ dbt project structure is valid!"
        
    - name: List models
      run: |
        cd dbt_project
        echo "📊 dbt Models found:"
        find models -name "*.sql" -type f | head -10
