name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install core dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core==1.6.6 dbt-postgres==1.6.6
        
    - name: Validate dbt project
      run: |
        cd dbt_project
        echo "🔍 Checking dbt project structure..."
        dbt debug --no-write-json || echo "⚠️  No database connection (expected in CI)"
        
        echo "✅ Parsing dbt models..."
        dbt parse --no-write-json
        
        echo "📊 Models found:"
        find models -name "*.sql" -type f | wc -l
        
        echo "🎉 dbt project validation successful!"
        
    - name: Code quality check
      run: |
        echo "📝 Checking Python files..."
        find scripts -name "*.py" -type f | wc -l || echo "No Python scripts found"
        
        echo "✅ Project structure validation complete!"
